# Generated by Django 5.2.1 on 2026-08-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_eventrequest_flyer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostedEvent",
        ),
        migrations.AlterModelOptions(
            name="eventrequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="eventrequest",
            name="is_posted",
        ),
        migrations.AlterField(
            model_name="eventrequest",
            name="flyer",
            field=models.ImageField(blank=True, null=True, upload_to="flyers/"),
        ),
        migrations.AlterField(
            model_name="eventrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("posted", "Posted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
