# Generated by Django 5.2.1 on 2025-06-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_organization_category_organization_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Technology", "Technology"),
                            ("Arts", "Arts"),
                            ("Health", "Health"),
                            ("Sports", "Sports"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("contact", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
