# Generated by Django 5.2.1 on 2025-06-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0003_eventrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrequest",
            name="org",
            field=models.CharField(default="Unknown Organization", max_length=100),
        ),
    ]
