# Generated by Django 5.2.1 on 2025-06-28 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0004_eventrequest_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrequest",
            name="is_posted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="eventrequest",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
