# Generated by Django 5.2.1 on 2025-06-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0006_postedevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="user_type",
            field=models.CharField(
                choices=[("student", "Student"), ("organization", "Organization")],
                default="organization",
                max_length=20,
            ),
        ),
    ]
