# Generated by Django 5.2.1 on 2025-07-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0007_organization_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrequest",
            name="flyer",
            field=models.ImageField(blank=True, null=True, upload_to="event_flyers/"),
        ),
    ]
